config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :twets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "twets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twet.rb
class Twet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :twets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation)

    end

    def acount_update_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation, :current_password)
    end
end

app/controllers/twets_controller.rb
class TwetsController < ApplicationController
  before_action :set_twet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except:[:index, :show]

  # GET /twets or /twets.json
  def index
    @twets = Twet.all.order("created_at DESC")
    @twet = Twet.new
  end

  # GET /twets/1 or /twets/1.json
  def show
  end

  # GET /twets/new
  def new
    @twet = current_user.twets.build
  end

  # GET /twets/1/edit
  def edit
  end

  # POST /twets or /twets.json
  def create
    @twet = current_user.twets.build(twet_params)

    respond_to do |format|
      if @twet.save
        format.html { redirect_to root_path, notice: "Twet was successfully created." }
        format.json { render :show, status: :created, location: @twet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twets/1 or /twets/1.json
  def update
    respond_to do |format|
      if @twet.update(twet_params)
        format.html { redirect_to @twet, notice: "Twet was successfully updated." }
        format.json { render :show, status: :ok, location: @twet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twets/1 or /twets/1.json
  def destroy
    @twet.destroy
    respond_to do |format|
      format.html { redirect_to twets_url, notice: "Twet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twet
      @twet = Twet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twet_params
      params.require(:twet).permit(:twet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twets_helper.rb
module TwetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%=notice %></p>
      </div>
    <%end%>

    <%if flash[:alert]%>
      <div class="notification is-danger global-notification">
      <p class="alert"><%=alert %></p>
      </div>
    <%end%>

    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Twetter</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span> 
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "New Twet", new_twet_path, class: "button is-info is-inverted" %> 
              </p>
              <p class="control">Sing Up</p>
            </div>
          </div>
      </div>
    </nav>



    <%= yield %>
  </body>
</html>

app/views/twets/_feed.html.erb
<div class="column is-half">
    <article class="media box">
        <figure class="media left">
            <p class="image is-64x64">
                <img src="https://bulma.io/images/placeholders/64x64.png">
            </p>
        </figure>

        <div class="media-content">
            <%= render 'twets/form' %>
        </div>
    </article>


<% @twets.each do |twet| %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong>content text</strong> <br/>
                    <small>smol</small> <br/>
                    <p> <%= twet.twet  %></p>
                </div>
                <nav class="level">
                    <div class="level-left is-mobile"> 
                        <%= link_to twet, class: "level-item" do %>
                            <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to edit_twet_path(twet), class: "level-item" do %>
                            <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to twet,method: :delete, data:{confirm: "Are you sure?"} do %>
                            <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                        <% end %>
                    </div>
                </nav>
            </div>
        </article>
    </div>
<% end %>
</div>

app/views/twets/_form.html.erb
<%= simple_form_for(@twet) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :twet, label: "Twet about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new twet...", autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
  <% end %>

app/views/twets/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			Trend 1
		</a>
		<a class="panel-block">
			Trend 2
		</a>
		<a class="panel-block">
			Trend 3
		</a>
		<a class="panel-block">
			Trend 4
		</a>
		<a class="panel-block">
			Trend 5
		</a>
		<a class="panel-block">
			Trend 6
		</a>
	</nav>
</div>

app/views/twets/_who-to-follow.html.erb
<div class="column">
<nav class="panel">
    <p class="panel-heading">Who to Follow</p>

<div class="panel-block">
    <article class="media">
        <div class="media-left">
            <figure class="image is-32x32">
                <img src="https://bulma.io/images/placeholders/64x64.png">
            </figure>
        </div>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>John Smith</strong>
                    <small>@johnsmith</small>
                </p>
            </div>
        </div>
    </article>
</div>
    <div class="panel-block">
    <article class="media">
        <div class="media-left">
            <figure class="image is-32x32">
                <img src="https://bulma.io/images/placeholders/64x64.png">
            </figure>
        </div>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>John Smith</strong>
                    <small>@johnsmith</small>
                </p>
            </div>
        </div>
    </article>
</div>
    <div class="panel-block">
    <article class="media">
        <div class="media-left">
            <figure class="image is-32x32">
                <img src="https://bulma.io/images/placeholders/64x64.png">
            </figure>
        </div>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>John Smith</strong>
                    <small>@johnsmith</small>
                </p>
            </div>
        </div>
    </article>
</div>
</nav>
</div>

app/views/twets/edit.html.erb
<h1>Editing Twet</h1>

<%= render 'form', twet: @twet %>

<%= link_to 'Show', @twet %> |
<%= link_to 'Back', twets_path %>

app/views/twets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'trends' %>
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/twets/new.html.erb
<h1>New Twet</h1>

<%= render 'form', twet: @twet %>

<%= link_to 'Back', twets_path %>

app/views/twets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Twet:</strong>
  <%= @twet.twet %>
</p>

<%= link_to 'Edit', edit_twet_path(@twet) %> |
<%= link_to 'Back', twets_path %>